on:
  push:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - master          # triggers on pushes that contain changes in master

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Checkout
      uses: actions/checkout@v1.0.0
    - name: Create artifact
      run: |
        zip --junk-paths Bearflow.alfredworkflow src/* images/*
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Bearflow.alfredworkflow
        path: Bearflow.alfredworkflow
